/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectFile = IDL.Record({
  'content' : IDL.Text,
  'filename' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Language = IDL.Variant({
  'cpp' : IDL.Null,
  'html_single' : IDL.Null,
  'javascript' : IDL.Null,
  'html_css_js' : IDL.Null,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Text,
  'isGlobal' : IDL.Bool,
  'files' : IDL.Vec(ProjectFile),
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'language' : Language,
  'updatedAt' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
});
export const Version = IDL.Record({
  'files' : IDL.Vec(ProjectFile),
  'versionId' : IDL.Text,
  'createdAt' : Time,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAIPreferenceRule' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addVersion' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(ProjectFile)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, Language, IDL.Vec(ProjectFile), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAIPreferenceRules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllGlobalProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getProjectVersions' : IDL.Func([IDL.Text], [IDL.Vec(Version)], ['query']),
  'getUser' : IDL.Func([], [User], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAIPreferenceRule' : IDL.Func([IDL.Nat], [], []),
  'removeMember' : IDL.Func([IDL.Principal], [], []),
  'revertToVersion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'seedDefaultClass6Users' : IDL.Func([], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, Language, IDL.Vec(ProjectFile), IDL.Bool],
      [],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectFile = IDL.Record({
    'content' : IDL.Text,
    'filename' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Language = IDL.Variant({
    'cpp' : IDL.Null,
    'html_single' : IDL.Null,
    'javascript' : IDL.Null,
    'html_css_js' : IDL.Null,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Text,
    'isGlobal' : IDL.Bool,
    'files' : IDL.Vec(ProjectFile),
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'language' : Language,
    'updatedAt' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
  });
  const Version = IDL.Record({
    'files' : IDL.Vec(ProjectFile),
    'versionId' : IDL.Text,
    'createdAt' : Time,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAIPreferenceRule' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addVersion' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(ProjectFile)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, Language, IDL.Vec(ProjectFile), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAIPreferenceRules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllGlobalProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getProjectVersions' : IDL.Func([IDL.Text], [IDL.Vec(Version)], ['query']),
    'getUser' : IDL.Func([], [User], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAIPreferenceRule' : IDL.Func([IDL.Nat], [], []),
    'removeMember' : IDL.Func([IDL.Principal], [], []),
    'revertToVersion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'seedDefaultClass6Users' : IDL.Func([], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, Language, IDL.Vec(ProjectFile), IDL.Bool],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };