/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Language = { 'cpp' : null } |
  { 'html_single' : null } |
  { 'javascript' : null } |
  { 'html_css_js' : null };
export interface Project {
  'id' : string,
  'isGlobal' : boolean,
  'files' : Array<ProjectFile>,
  'title' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'language' : Language,
  'updatedAt' : Time,
}
export interface ProjectFile { 'content' : string, 'filename' : string }
export type Time = bigint;
export interface User {
  'id' : Principal,
  'username' : string,
  'createdAt' : Time,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Version {
  'files' : Array<ProjectFile>,
  'versionId' : string,
  'createdAt' : Time,
  'prompt' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAIPreferenceRule' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[Principal, string], undefined>,
  'addVersion' : ActorMethod<[string, string, Array<ProjectFile>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, Language, Array<ProjectFile>, boolean],
    string
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAIPreferenceRules' : ActorMethod<[], Array<string>>,
  'getAllGlobalProjects' : ActorMethod<[], Array<Project>>,
  'getCallerProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], Project>,
  'getProjectVersions' : ActorMethod<[string], Array<Version>>,
  'getUser' : ActorMethod<[], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAIPreferenceRule' : ActorMethod<[bigint], undefined>,
  'removeMember' : ActorMethod<[Principal], undefined>,
  'revertToVersion' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'seedDefaultClass6Users' : ActorMethod<[], undefined>,
  'updateProject' : ActorMethod<
    [string, string, Language, Array<ProjectFile>, boolean],
    undefined
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];